POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "1001",
  "password": "1001"
}
> {% client.global.set("token3",response.headers.valueOf("authorization")); %}

###
GET http://localhost:8080/api/admin/students
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/teachers
authorization: {{token3}}
Accept: application/json

####

POST http://localhost:8080/api/admin/students
authorization: {{token3}}
Content-Type: application/json

{
  "user": {
    "number": 2001,
    "name": "2001",
    "role": "STUDENT"
  }
}

####

POST http://localhost:8080/api/admin/teachers
authorization: {{token3}}
Content-Type: application/json

{
  "user": {
    "number": 3002,
    "name": "3002",
    "role": "TEACHER"
  }
}

####


DELETE http://localhost:8080/api/admin/teachers/49
authorization: {{token3}}
Accept: application/json

###
DELETE http://localhost:8080/api/admin/students/4
authorization: {{token3}}
Accept: application/json

###


PATCH http://localhost:8080/api/admin/user/3
Content-Type: application/json
authorization: {{token3}}


  {
    "id": 3,
    "name": "花花呀",
    "number": 1990,
    "role": "ADMINISTRATOR",
    "insertTime": "2020-07-10T16:14:32"
  }



###

###

POST http://localhost:8080/api/admin/user/teacher
authorization: {{token3}}
Content-Type: application/json

{
  "number": 1990,
  "name": "花花呀",
  "password": "1990"
}


###

POST http://localhost:8080/api/admin/user/admin
authorization: {{token3}}
Accept: application/json

###

GET http://localhost:8080/api/admin/student
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/role/STUDENT
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/onlineExamList
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/onlineExamId/1
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/userName
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/role/ADMINISTRATOR
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/students
authorization: {{token3}}
Accept: application/json

####

GET http://localhost:8080/api/admin/teachers
authorization: {{token3}}
Accept: application/json

####